services:
  api:
    extends:
      file: developers-italia-api/docker-compose.yml
      service: api
    environment:
      - PASETO_KEY=${PASETO_KEY}

  db:
    extends:
      file: developers-italia-api/docker-compose.yml
      service: db
